### ISSUE TITLE
 Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by 523931340** [Bilibili/boxing#10]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@6d2f883
                                                                         at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1301)
                                                                         at android.graphics.Canvas.drawBitmap(Canvas.java:1435)
                                                                         at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:551)
                                                                         at android.widget.ImageView.onDraw(ImageView.java:1270)
                                                                         at android.view.View.draw(View.java:17469)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                         at android.view.View.draw(View.java:17238)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.draw(View.java:17472)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                         at android.view.View.draw(View.java:17238)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.draw(View.java:17472)
                                                                         at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                         at android.view.View.draw(View.java:17238)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16459)
                                                                         at android.view.View.draw(View.java:17238)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.draw(View.java:17472)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                         at android.view.View.draw(View.java:17238)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16459)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ChenSiLiang** [comment]
how to throw this exception , in which activity?

**Comment by 523931340** [comment]
in BoxingActivity,when i want to change the  folder

**Comment by ChenSiLiang** [comment]
which loader you use?

**Comment by 523931340** [comment]
BoxingFrescoLoader( Samsung SM-G9200 Android 6.0.1 API 23)

**Comment by ChenSiLiang** [comment]
I try the same phone and all things are right.
Avoid using recycled bitmap already In `BoxingFrescoLoader`
```java
if (bitmap == null || bitmap.isRecycled()) {
       onFailureImpl(dataSource);
       return;
}
```
maybe you can provider more detail?

**Comment by 523931340** [comment]
@ChenSiLiang 换成Glide加载图片没有这个问题...

**Comment by Xuzhiwei** [comment]
其实在loadImage方法里面，有一行CloseableReference的对象，CloseableReference<CloseableImage> result = dataSource.getResult();
在finally的时候对它进行了                    CloseableReference.closeSafely(result);
了，所以会出这问题，只要改成
                CloseableReference<CloseableImage> result = dataSource.getResult().clone();
就可以解决了。

**Comment by ChenSiLiang** [comment]
用Frescoloader的话要用它的控件drawee
