### ISSUE TITLE
RecyclerView Bug

### ISSUE THREAD

**Issue by 751496032** [Bilibili/boxing#109]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{604332b position=24 id=-1, oldPos=-1, pLpos:-1 no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5046)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5177)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:562)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1225)
	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1045)
	at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1642)
	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2764)
	at android.view.View.dispatchTouchEvent(View.java:9333)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2564)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2250)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)

**Comment by ChenSiLiang** [comment]
已修复。
