### ISSUE TITLE
快速滑动的时候立即切换相册容易引发此异常 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhengjiong** [Bilibili/boxing#111]
**快速滑动的时候立即切换相册容易引发此异常**, 使用boxing1.0.0版本, fresco1.5版本
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{7e56bfd position=117 id=-1, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{d4b2057 VFED.V... .F...... 0,0-1440,2112 #7f090255 app:id/media_recycleview}, adapter:com.bilibili.boxing_impl.adapter.BoxingMediaAdapter@7217744, layout:android.support.v7.widget.GridLayoutManager@e2eb02d, context:com.bilibili.boxing_impl.ui.BoxingActivity@b31309c
                                                                        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5421)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5603)
                                                                        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ChenSiLiang** [comment]
已修复。
