### ISSUE TITLE
点击拍照奔溃

### ISSUE THREAD

**Issue by Jonnylee0012** [Bilibili/boxing#140]
Process: com.marsblock.app, PID: 1511
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
        at com.bilibili.boxing.utils.CameraPickerHelper.getFileUri(CameraPickerHelper.java:183)
        at com.bilibili.boxing.utils.CameraPickerHelper.startCameraIntent(CameraPickerHelper.java:166)
        at com.bilibili.boxing.utils.CameraPickerHelper.takePhotoSecure(CameraPickerHelper.java:129)
        at com.bilibili.boxing.utils.CameraPickerHelper.startCamera(CameraPickerHelper.java:98)
        at com.bilibili.boxing.AbsBoxingViewFragment.startCamera(AbsBoxingViewFragment.java:441)
        at com.bilibili.boxing_impl.ui.BoxingViewFragment$OnCameraClickListener.onClick(BoxingViewFragment.java:462)
        at android.view.View.performClick(View.java:6891)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by ChenSiLiang** [comment]
检查是否配置权限
