### ISSUE TITLE
图片预览闪退,报方法找不到

### ISSUE THREAD

**Issue by zhw634631** [Bilibili/boxing#155]
这个是错误日志
` UncaughtException detected: java.lang.NoSuchMethodError: No virtual method setRotatable(Z)V in class Luk/co/senab/photoview/PhotoViewAttacher; or its super classes (declaration of 'uk.co.senab.photoview.PhotoViewAttacher' appears in /data/app/com.jumeng.lsj-WSHFzcu7uioHpBgXaXR8Eg==/base.apk!classes3.dex)
        at com.bilibili.boxing_impl.ui.BoxingRawImageFragment.onViewCreated(BoxingRawImageFragment.java:85)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
`
我集成的包是 implementation 'com.bilibili:boxing-impl:1.0.4'

**Comment by zhoufeng1213** [comment]
加上这句：
implementation('com.chensl.rotatephotoview:rotatephotoview:1.0.5') {
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
    }
