### ISSUE TITLE
Android 10 crash

### ISSUE THREAD

**Issue by xiaoyuanhu** [Bilibili/boxing#159]
Fatal Exception: android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name FROM images WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND ((0==0) GROUP BY(bucket_id)) ORDER BY date_modified desc
       at android.database.DatabaseUtils.readExceptionFromParcel + 184(DatabaseUtils.java:184)
       at android.database.DatabaseUtils.readExceptionFromParcel + 140(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query + 423(ContentProviderNative.java:423)
       at android.content.ContentResolver.query + 934(ContentResolver.java:934)
       at android.content.ContentResolver.query + 872(ContentResolver.java:872)
       at android.content.ContentResolver.query + 830(ContentResolver.java:830)
       at com.bilibili.boxing.model.task.impl.AlbumTask.buildAlbumInfo + 72(AlbumTask.java:72)
       at com.bilibili.boxing.model.task.impl.AlbumTask.start + 64(AlbumTask.java:64)
       at com.bilibili.boxing.model.BoxingManager$2.run + 74(BoxingManager.java:74)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 919(Thread.java:919)

**Comment by Mysqi** [comment]
I also have this situation.

**Comment by zhuzhao404** [comment]
"GROUP BY(" dismiss space “GROUP BY (”

**Comment by masterTail** [comment]
android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name FROM images WHERE ((is_pending=0) AND (is_trashed=0)) AND ((0==0) GROUP BY(bucket_id)) ORDER BY date_modified desc
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:936)
        at android.content.ContentResolver.query(ContentResolver.java:873)
        at android.content.ContentResolver.query(ContentResolver.java:831)
        at com.bilibili.boxing.model.task.impl.AlbumTask.buildAlbumInfo(AlbumTask.java:72)
        at com.bilibili.boxing.model.task.impl.AlbumTask.start(AlbumTask.java:64)
        at com.bilibili.boxing.model.BoxingManager$2.run(BoxingManager.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
我这边也是这样的，当图库没有一张图片，且在Android Q的系统上，该问题必现

**Comment by kaiyuanshengshichangan** [comment]
> "GROUP BY(" dismiss space “GROUP BY (”

加了空格后仍然报错

**Comment by zzzmobile** [comment]
please add space in ln: 72 in AlbumTask.java
..."0==0)" + "[space]GROUP BY[space]("...

It worked for me.

**Comment by tikeyc** [comment]
这个BUG 作者是不准备解决了吗？

**Comment by HumphreySs** [comment]
加了空格解决了。
