### ISSUE TITLE
模拟器点击图片选择闪退

### ISSUE THREAD

**Issue by thundeGG** [Bilibili/boxing#161]
下面的方法报错： 
private void buildAlbumInfo(ContentResolver cr) {
        String[] distinctBucketColumns = new String[]{Media.BUCKET_ID, Media.BUCKET_DISPLAY_NAME};
        Cursor bucketCursor = null;
        try {
            bucketCursor = cr.query(Media.EXTERNAL_CONTENT_URI, distinctBucketColumns, "0==0)" + " GROUP BY(" + Media.BUCKET_ID, null,
                    Media.DATE_MODIFIED + " desc");
            if (bucketCursor != null && bucketCursor.moveToFirst()) {
                do {
                    String buckId = bucketCursor.getString(bucketCursor.getColumnIndex(Media.BUCKET_ID));
                    String name = bucketCursor.getString(bucketCursor.getColumnIndex(Media.BUCKET_DISPLAY_NAME));
                    AlbumEntity album = buildAlbumInfo(name, buckId);
                    if (!TextUtils.isEmpty(buckId)) {
                        buildAlbumCover(cr, buckId, album);
                    }
                } while (bucketCursor.moveToNext());
            }
        } finally {
            if (bucketCursor != null) {
                bucketCursor.close();
            }
        }
    }

**Comment by thundeGG** [comment]
日志如下：
Process: com.thunder.fox_app, PID: 20112
    android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name FROM images WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' , '0d18-2914' ))) AND ((0==0) GROUP BY(bucket_id)) ORDER BY date_modified desc
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.bilibili.boxing.model.task.impl.AlbumTask.buildAlbumInfo(AlbumTask.java:72)
        at com.bilibili.boxing.model.task.impl.AlbumTask.start(AlbumTask.java:64)
        at com.bilibili.boxing.model.BoxingManager$2.run(BoxingManager.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-08-12 15:49:21.312 15407-15488/system_process E/InputDispatcher: channel 'aa32642 com.thunder.fox_app/com.thunder.fox_app.modules.login.ui.PerfectInformationActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-08-12 15:49:21.541 15968-19654/com.google.android.gms.persistent E/ctxmgr: [NetworkUtil] No active synchronizable contexts. [CONTEXT service_id=47 ]
2019-08-12 15:49:26.751 20245-20245/? E/thunder.fox_ap: Unknown bits set in runtime_flags: 0x8000
2019-08-12 15:49:27.092 20245-20272/? E/ARouter: Scan map file in dex files made error.
    java.io.IOException: No original dex files found for dex location /data/app/com.thunder.fox_app-hNcFKhqimpweUHX0n6bxIw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:92)
        at com.alibaba.android.arouter.utils.ClassUtils$1.run(ClassUtils.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-08-12 15:49:27.275 1688-1688/? E/Layer: [Surface(name=AppWindowToken{32c66d1 token=Token{a6711f8 ActivityRecord{d8655b u0 com.thunder.fox_app/.modules.login.ui.PerfectInformationActivity t31}}})/@0xf2db53c - animation-leash#0] No local sync point found
2019-08-12 15:49:27.275 1688-1688/? E/Layer: [Surface(name=AppWindowToken{4804189 token=Token{93b4490 ActivityRecord{b168742 u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t15}}})/@0xa4117eb - animation-leash#0] No local sync point found
2019-08-12 15:49:27.363 1688-2000/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2019-08-12 15:49:27.364 1688-1806/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2019-08-12 15:49:27.679 20245-20285/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2019-08-12 15:49:27.679 20245-20285/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2019-08-12 15:49:37.443 15407-15434/system_process E/memtrack: Couldn't load memtrack module
2019-08-12 15:49:47.907 15407-15434/system_process E/memtrack: Couldn't load memtrack module
2019-08-12 15:50:11.419 1826-1826/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2019-08-12 15:50:11.419 1826-1826/? E/netmgr: WifiForwarder unable to open QEMU pipe: Invalid argument
2019-08-12 15:50:41.081 15407-15520/system_process E/ClipboardService: Denying clipboard access to com.android.chrome, application is not in focus neither is a system service for user 0
2019-08-12 15:50:50.617 15407-15434/system_process E/memtrack: Couldn't load memtrack module
2019-08-12 15:50:51.984 15968-20299/com.google.android.gms.persistent E/GCM: Missing checkin config file
2019-08-12 15:50:51.991 15968-20299/com.google.android.gms.persistent E/GCM: Missing checkin config file
2019-08-12 15:50:52.010 15968-20299/com.google.android.gms.persistent E/WakeLock: GCM_HB_ALARM release without a matched acquire!
2019-08-12 15:50:52.103 15348-20306/? E/ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
2019-08-12 15:50:52.836 15968-20305/com.google.android.gms.persistent E/GCM: Missing checkin config file
2019-08-12 15:50:52.838 15968-20305/com.google.android.gms.persistent E/GCM: Missing checkin config file
2019-08-12 15:50:52.844 15968-20305/com.google.android.gms.persistent E/WakeLock: GCM_HB_ALARM release without a matched acquire!
2019-08-12 15:50:54.017 15407-16320/system_process E/memtrack: Couldn't load memtrack module
2019-08-12 15:51:11.422 1826-1826/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2019-08-12 15:51:11.422 1826-1826/? E/netmgr: WifiForwarder unable to open QEMU pipe: Invalid argument
2019-08-12 15:51:19.625 15968-20241/com.google.android.gms.persistent E/GCM: Missing checkin config file

**Comment by gongkaiqiang** [comment]
我也遇到了相同的问题

**Comment by yangjunorg** [comment]
有人解决了么？
