### ISSUE TITLE
Android Q SQLiteException

### ISSUE THREAD

**Issue by a7819923** [Bilibili/boxing#163]
android.database.sqlite.SQLiteException:  near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name FROM images WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( '1101-170b' , 'external_primary' ))) AND ((0==0) GROUP BY(bucket_id)) ORDER BY date_modified desc
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.bilibili.boxing.model.b.a.a.a(AlbumTask.java:73)
        at com.bilibili.boxing.model.b.a.a.a(AlbumTask.java:65)
        at com.bilibili.boxing.model.b$2.run(BoxingManager.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by hexianqiao3755** [comment]
same question

**Comment by wj19940612** [comment]
When will the same problem be solved

**Comment by hujlin** [comment]
same question

**Comment by ning767566973** [comment]
+1

**Comment by gongkaiqiang** [comment]
+1

**Comment by TerrenceYY** [comment]
+1

**Comment by aii1991** [comment]
same problem
