### ISSUE TITLE
Android 11也报错了

### ISSUE THREAD

**Issue by 1794208519** [Bilibili/boxing#168]

**Comment by beibeiandroid** [comment]
Thread Name: 'pool-13-thread-1'
Back traces starts.
java.lang.IllegalArgumentException: Invalid token LIMIT
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1195)
	at android.content.ContentResolver.query(ContentResolver.java:1127)
	at android.content.ContentResolver.query(ContentResolver.java:1083)
	at com.bilibili.boxing.model.task.impl.ImageTask.query(ImageTask.java:171)
	at com.bilibili.boxing.model.task.impl.ImageTask.buildAlbumList(ImageTask.java:118)
	at com.bilibili.boxing.model.task.impl.ImageTask.load(ImageTask.java:75)
	at com.bilibili.boxing.model.BoxingManager$1.run(BoxingManager.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Back traces ends.
