### ISSUE TITLE
关于崩溃和适配的问题，可以看这里

### ISSUE THREAD

**Issue by toeii** [Bilibili/boxing#170]
因为项目需要，拉了一个分支，将基于boxing进行维护和升级。地址：https://github.com/toeii/boxing

**Comment by breakadmin** [comment]
那边好像不能提issues,可以迁移androidx了

**Comment by breakadmin** [comment]
算了别迁移了,android10一样的报错

**Comment by breakadmin** [comment]
android 10一样的报错....

**Comment by toeii** [comment]
@breakadmin 错误信息发一下

**Comment by breakadmin** [comment]
就是这个错

android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name FROM images WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( '1101-170b' , 'external_primary' ))) AND ((0==0) GROUP BY(bucket_id)) ORDER BY date_modified desc
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
at android.content.ContentResolver.query(ContentResolver.java:944)
at android.content.ContentResolver.query(ContentResolver.java:880)
at android.content.ContentResolver.query(ContentResolver.java:836)
at com.bilibili.boxing.model.b.a.a.a(AlbumTask.java:73)
at com.bilibili.boxing.model.b.a.a.a(AlbumTask.java:65)
at com.bilibili.boxing.model.b$2.run(BoxingManager.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

**Comment by toeii** [comment]
@breakadmin https://github.com/toeii/boxing

**Comment by breakadmin** [comment]
就是用的你这个  implementation 'com.github.toeii:boxing:v1.0.5'，代码我都看过了,改都没改到

**Comment by toeii** [comment]
@breakadmin 等回去我看一下，如果很急你自己拉分支改

**Comment by breakadmin** [comment]
改过了,小米上还有其他问题
![Uploading Screenshot_2020-09-25-10-59-32-892_com.jpnight.app.jpg…]()

**Comment by breakadmin** [comment]
> 改过了,小米手机上还有其它问题``,首次加载相册目录只显示一个问号

**Comment by toeii** [comment]
@breakadmin 没有设备文件的读取权限导致的，引导用户同意就行了

**Comment by breakadmin** [comment]
在华为手机都运行的好好的,没权限??我...真无语

**Comment by shaycormac** [comment]
你好，请问有计划弄一个target=Q的版本么，谢谢。

**Comment by 1656150492** [comment]
楼主 你忽悠我！  你说改了圆形裁剪  只是在bean里加了一个boolean的set，get
