### ISSUE TITLE
小米5s 多选闪退

### ISSUE THREAD

**Issue by a48352433** [Bilibili/boxing#26]
小米5s运行demo,多选图片时闪退.6.0.1  miui8 7.3.16开发版

`AndroidRuntime: java.lang.ClassCastException: com.facebook.imagepipeline.image.CloseableAnimatedImage cannot be castto com.facebook.imagepipeline.image.CloseableStaticBitmap
  at com.bilibili.boxing.impl.BoxingFrescoLoader$1.onNewResultImpl(BoxingFrescoLoader.java:115)
  at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:48)
  at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:181)
  at android.os.Handler.handleCallback(Handler.java:742)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:5486)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by ChenSiLiang** [comment]
已修复

**Comment by a48352433** [comment]
高效啊!
