### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.bilibili.boxing.presenter.PickerContract$Presenter.loadMedias(int, java.lang.String)'

### ISSUE THREAD

**Issue by ShinChven** [Bilibili/boxing#36]
app  Activity 在后台被内存回收之后，重新onStart方法会挂~

 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.bilibili.boxing.presenter.PickerContract$Presenter.loadMedias(int, java.lang.String)' on a null object reference
                                                                                   at com.bilibili.boxing.AbsBoxingViewFragment.loadMedias(AbsBoxingViewFragment.java:357)
                                                                                   at com.bilibili.boxing_impl.ui.BoxingBottomSheetFragment.startLoading(BoxingBottomSheetFragment.java:172)
                                                                                   at com.bilibili.boxing.AbsBoxingViewFragment.checkPermissionAndLoad(AbsBoxingViewFragment.java:187)
                                                                                   at com.bilibili.boxing.AbsBoxingViewFragment.onViewCreated(AbsBoxingViewFragment.java:178)
                                                                                   at com.bilibili.boxing_impl.ui.BoxingBottomSheetFragment.onViewCreated(BoxingBottomSheetFragment.java:84)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
                                                                                   at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2832)
                                                                                   at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                                   at ***.MainActivity.onStart(MainActivity.java:523)
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                                   at android.app.Activity.performStart(Activity.java:6699)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ChenSiLiang** [comment]
已修复

**Comment by ShinChven** [comment]
3Q @ChenSiLiang
