### ISSUE TITLE
点击预览图片的时候出错

### ISSUE THREAD

**Issue by zj-wukewei** [Bilibili/boxing#37]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@cc64ef4
                                                                      at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                      at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
                                                                      at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
                                                                      at android.widget.ImageView.onDraw(ImageView.java:1246)
                                                                      at android.view.View.draw(View.java:16201)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                      at android.view.View.draw(View.java:15971)
我使用的是Fresco图片库，BoxingRawImageFragment的BoxingCallback类也是能调onSuccess的

**Comment by ChenSiLiang** [comment]
已修复
