### ISSUE TITLE
请问拿到图片的imageMedia.getPath()后,如何将这张图片通过retrofit上传给远端?

### ISSUE THREAD

**Issue by jesse920524** [Bilibili/boxing#43]
我的代码:  
File file = new File(path);
        RequestBody avatarRequestBody = RequestBody.create(MediaType.parse("image/png"), file);
        MultipartBody.Part avatar = MultipartBody.Part.createFormData("photos", "icon.png", avatarRequestBody);

presenter.sendModifyAvatarRequest(avatar, entity.getToken(), UtilDevice.getAndroidId(), UtilDevice.getTime(), entity.getUserId(), entity.getNickName(), UtilDevice.beginHashReStr(map));

会报错误:
W/System.err: java.io.FileNotFoundException: file:/data/user/0/xique.yinwei.ren/cache/boxing/1492675723592.jpg: open failed: ENOENT (No such file or directory)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okio.Okio.source(Okio.java:168)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.RequestBody$3.writeTo(RequestBody.java:117)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:756)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:244)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:209)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8460)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-20 16:08:48.831 7233-7233/xique.yinwei.ren W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err:     at libcore.io.Posix.open(Native Method)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
04-20 16:08:48.832 7233-7233/xique.yinwei.ren W/System.err: 	... 31 more

**Comment by jesse920524** [comment]
自问自答:
使用MultiPart方式上传单张图片到服务器.
构建图片@Part MultipartBody.Part

 File file = new File(path);
        RequestBody avatarRequestBody = RequestBody.create(MediaType.parse("image/png"), file);
        MultipartBody.Part avatar = MultipartBody.Part.createFormData("photos", "icon.png", avatarRequestBody);

path为boxing类库返回的ImageMedia.getPath()拿到.

感谢boxing类库的作者.
