### ISSUE TITLE
通过compile进行依赖会出现Manifest文件冲突

### ISSUE THREAD

**Issue by AndRickyChan** [Bilibili/boxing#50]
通过compile进行项目依赖的时候，会出现Manifest文件出现label名字冲突，必须要使用box_app_name才会编译通过，建议作者删除library包中的application节点，或者请给我一个能够解决这个问题的建议，谢谢。

**Comment by ChenSiLiang** [comment]
可以再application节点内添加`tools:replace="android:label"`

**Comment by diorslau** [comment]
楼上说的这个是加到自己工程的application节点吗?   我加了好像也没有用  运行还是报错的

**Comment by ChenSiLiang** [comment]
是的 我测试过是可以的 具体报什么错呢？

**Comment by diorslau** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/MyAppTheme) from AndroidManifest.xml:46:9-42
	is also present at [com.bilibili:boxing-impl:0.7.0] AndroidManifest.xml:31:9-47 value=(@style/Boxing.AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:39:5-327:19 to override.

**Comment by diorslau** [comment]
好像是说theme也冲突了吧,  这个要怎么加呢?

**Comment by diorslau** [comment]
tools:replace="android:label,android:theme"   解决了, 这样添加就行了

**Comment by linzhengloser** [comment]
boxing中的manifest 和我导入的第三方jar的manifest冲突了,请问下这个怎么解决？

**Comment by ChenSiLiang** [comment]
@linzhengloser 是什么冲突 贴出错误信息

**Comment by chaimingkun** [comment]
@ChenSiLiang 楼上的意思就是两个第三方的aar的manifest application节点的属性冲突了，作为一个第三方引入的包，manifest application下的节点不应该有属性的吧？

**Comment by ChenSiLiang** [comment]
@chaimingkun lib库里面的节点已经全部删除，如果用ui库的话按上面讨论的就应该可以解决

**Comment by chaimingkun** [comment]
👍效率好高，我也准备用你们的这个库，写的太棒了

**Comment by liudaoxiang** [comment]
你好，在华为手机MHA-AL00 Android 7.0，拍照后发生下面这个错误：

06-07 14:53:34.409 16945-17217/? E/SQLiteDatabase: Error inserting hash=5ec85da8ae5522b3aeccac9e64249c6a datetaken=1496818412000 bucket_display_name=boxing duration=0 local_media_id=31535 mime_type=image/jpeg hw_voice_offset=0 contenturi=null orientation=0 _display_name=1496818398352.jpg special_file_type=0 bucket_id=1894470992 longitude=0.0 is_hdr=0 height=0 date_modified=1496818412 is_hw_burst=0 bucket_relative_path=/DCIM/bili/boxing storage_id=65537 hw_rectify_offset=0 media_type=1 description=null title=1496818412718 _data=/storage/emulated/0/DCIM/bili/boxing/1496818398352.jpg _size=3898960 is_hw_favorite=0 latitude=0.0 date_added=1496818412 width=0 resolution=null is_hw_privacy=0 special_file_list=0 hw_image_refocus=0
                                                   android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: gallery_media._data (Sqlite code 2067), (OS error - 88:Socket operation on non-socket)
                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:792)
                                                       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
                                                       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1720)
                                                       at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1586)
                                                       at com.huawei.gallery.provider.GalleryProvider.insertInternal(GalleryProvider.java:252)
                                                       at com.huawei.gallery.provider.GalleryProvider.insert(GalleryProvider.java:203)
                                                       at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
                                                       at android.content.ContentResolver.insert(ContentResolver.java:1291)
                                                       at com.huawei.gallery.media.GalleryMedia.insert(GalleryMedia.java:297)
                                                       at com.huawei.gallery.media.LocalSyncToken.insertLocalMediaItem(LocalSyncToken.java:314)
                                                       at com.huawei.gallery.media.LocalSyncToken.syncBatch(LocalSyncToken.java:222)
                                                       at com.huawei.gallery.media.MediaSyncerService.syncWithOperation(MediaSyncerService.java:97)
                                                       at com.huawei.gallery.media.MediaSyncerService.handleMessage(MediaSyncerService.java:70)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by magical-xu** [comment]
作者，请问为什么 gradle里引入 design包 和 v7包的时候 不使用 provided 关键字引入呢？这样就不需要
compile的时候再手动 exclude掉冲突的库了
