### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by diorslau** [Bilibili/boxing#51]
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.SecurityException: Provider must grant uri permissions
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:5814)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                                                                        at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                     Caused by: java.lang.SecurityException: Provider must grant uri permissions
                                                                        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:372)
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
                                                                        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

集成lib后运行 就报这个错, 请问下这个权限要怎么弄?

这是我的配置
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file.provider" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:exported="false"
                android:grantUriPermissions="true"
                android:resource="@xml/boxing_file_provider"/>
        </provider>

**Comment by diorslau** [comment]
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file.provider" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:exported="false"
                android:grantUriPermissions="true"
                android:resource="@xml/boxing_file_provider"/>
        </provider>

**Comment by jaysdev** [comment]
建议去网上搜下File Provider的相关资料,再看看demo里面的写法。

[https://github.com/Bilibili/boxing/blob/master/app/src/main/AndroidManifest.xml](url)

**Comment by ChenSiLiang** [comment]
[参考官网说明](https://developer.android.com/reference/android/support/v4/content/FileProvider.html)或demo里的写法。

**Comment by diorslau** [comment]
我的写法跟你demo是一样的  手机型号是 nokia 7.0 系统

**Comment by ChenSiLiang** [comment]
确定android:grantUriPermissions在provider里面？我看上面贴的源码时在meta-data里的
```xml

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file.provider"
            android:exported="false"
            android:grantUriPermissions="true">

            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/boxing_file_provider"/>

        </provider>
```
