### ISSUE TITLE
华为手机MHA-AL00 Android 7.0，拍照后发生错误

### ISSUE THREAD

**Issue by liudaoxiang** [Bilibili/boxing#67]
你好，在华为手机MHA-AL00 Android 7.0，拍照后发生下面这个错误：

06-07 14:53:34.409 16945-17217/? E/SQLiteDatabase: Error inserting hash=5ec85da8ae5522b3aeccac9e64249c6a datetaken=1496818412000 bucket_display_name=boxing duration=0 local_media_id=31535 mime_type=image/jpeg hw_voice_offset=0 contenturi=null orientation=0 _display_name=1496818398352.jpg special_file_type=0 bucket_id=1894470992 longitude=0.0 is_hdr=0 height=0 date_modified=1496818412 is_hw_burst=0 bucket_relative_path=/DCIM/bili/boxing storage_id=65537 hw_rectify_offset=0 media_type=1 description=null title=1496818412718 _data=/storage/emulated/0/DCIM/bili/boxing/1496818398352.jpg _size=3898960 is_hw_favorite=0 latitude=0.0 date_added=1496818412 width=0 resolution=null is_hw_privacy=0 special_file_list=0 hw_image_refocus=0
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: gallery_media._data (Sqlite code 2067), (OS error - 88:Socket operation on non-socket)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:792)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1720)
at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1586)
at com.huawei.gallery.provider.GalleryProvider.insertInternal(GalleryProvider.java:252)
at com.huawei.gallery.provider.GalleryProvider.insert(GalleryProvider.java:203)
at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
at android.content.ContentResolver.insert(ContentResolver.java:1291)
at com.huawei.gallery.media.GalleryMedia.insert(GalleryMedia.java:297)
at com.huawei.gallery.media.LocalSyncToken.insertLocalMediaItem(LocalSyncToken.java:314)
at com.huawei.gallery.media.LocalSyncToken.syncBatch(LocalSyncToken.java:222)
at com.huawei.gallery.media.MediaSyncerService.syncWithOperation(MediaSyncerService.java:97)
at com.huawei.gallery.media.MediaSyncerService.handleMessage(MediaSyncerService.java:70)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:156)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ChenSiLiang** [comment]
主键冲突了，是每次拍照都这样？

**Comment by liudaoxiang** [comment]
抱歉！那么久才回复你。

是的。在这个型号的手机上面一直出现。
