### ISSUE TITLE
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class

### ISSUE THREAD

**Issue by liujia95** [Bilibili/boxing#71]
```java
//传了selectMedias就报如下错
Boxing.of(config).withIntent(this, BoxingActivity.class,selectMedias).start(this, 101);
```
```cmd
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aglhz.yicommunity/com.bilibili.boxing_impl.ui.BoxingActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class com.aglhz.yicommunity.main.publish.view.PublishNeighbourFragment$1
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5308)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
                                                                      Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class com.aglhz.yicommunity.main.publish.view.PublishNeighbourFragment$1
                                                                         at android.os.Parcel.readParcelableCreator(Parcel.java:2304)
                                                                         at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                                         at android.os.Parcel.readValue(Parcel.java:2152)
                                                                         at android.os.Parcel.readListInternal(Parcel.java:2526)
                                                                         at android.os.Parcel.readArrayList(Parcel.java:1842)
                                                                         at android.os.Parcel.readValue(Parcel.java:2173)
                                                                         at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                                                         at android.os.BaseBundle.unparcel(BaseBundle.java:224)
                                                                         at android.os.Bundle.getParcelableArrayList(Bundle.java:799)
                                                                         at android.content.Intent.getParcelableArrayListExtra(Intent.java:5121)
                                                                         at com.bilibili.boxing.AbsBoxingActivity.getSelectedMedias(AbsBoxingActivity.java:52)
                                                                         at com.bilibili.boxing.AbsBoxingActivity.onCreate(AbsBoxingActivity.java:44)
                                                                         at com.bilibili.boxing_impl.ui.BoxingActivity.onCreate(BoxingActivity.java:47)
                                                                         at android.app.Activity.performCreate(Activity.java:6049)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5308) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
```

**Comment by ChenSiLiang** [comment]
这个selectedmedias是已选的实体类list，没已选的可以不填。

**Comment by ChenSiLiang** [comment]
这个selectedmedias是已选的实体类list，没已选的可以不填。

**Comment by liujia95** [comment]
感谢回复，是我设置错误，该问题可关闭。
