### ISSUE TITLE
模拟器拍照报错

### ISSUE THREAD

**Issue by timasuperapp** [Bilibili/boxing#76]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                  at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                  at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                  at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                  at com.bilibili.boxing.utils.CameraPickerHelper.getFileUri(CameraPickerHelper.java:183)
                                                                  at com.bilibili.boxing.utils.CameraPickerHelper.startCameraIntent(CameraPickerHelper.java:166)
                                                                  at com.bilibili.boxing.utils.CameraPickerHelper.takePhotoSecure(CameraPickerHelper.java:129)
                                                                  at com.bilibili.boxing.utils.CameraPickerHelper.startCamera(CameraPickerHelper.java:98)
                                                                  at com.bilibili.boxing.AbsBoxingViewFragment.startCamera(AbsBoxingViewFragment.java:438)
                                                                  at com.jmc.apppro.window.views.boxing.BoxingViewFragment$OnCameraClickListener.onClick(BoxingViewFragment.java:437)
                                                                  at android.view.View.performClick(View.java:5610)
                                                                  at android.view.View$PerformClick.run(View.java:22265)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ChenSiLiang** [comment]
fileprovider配了么？

**Comment by timasuperapp** [comment]
我的编译版本是22
