### ISSUE TITLE
预览大图奔溃

### ISSUE THREAD

**Issue by lihuaye** [Bilibili/boxing#94]
代码：
```kotlin
  Boxing.of(BoxingConfig.Mode.MULTI_IMG).withIntent(this, BoxingViewActivity::class.java, selectedImages, position).start(this, REQUEST_IMAGES)
```
错误日志：
`FATAL EXCEPTION: main
                                                                        Process: cn.edu.xmut.onlinepark, PID: 12914
                                                                        java.lang.NoSuchMethodError: No virtual method setRotatable(Z)V in class Luk/co/senab/photoview/PhotoViewAttacher; or its super classes (declaration of 'uk.co.senab.photoview.PhotoViewAttacher' appears in /data/app/cn.edu.xmut.onlinepark-2/base.apk:classes31.dex)
                                                                            at com.bilibili.boxing_impl.ui.BoxingRawImageFragment.onViewCreated(BoxingRawImageFragment.java:85)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                            at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                            at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                            at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                            at android.view.View.measure(View.java:19965)
                                                                            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2309)
                                                                            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1392)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1645)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6432)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
08-28 17:16:42.762 12914-12914/cn.edu.xmut.onlinepark E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6369)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by ChenSiLiang** [comment]
用了其他photoview库？

**Comment by lihuaye** [comment]
@ChenSiLiang 嗯，用了bga-photopicker这个库，有什么好的解决方法，求告知

**Comment by HuangMingFrancis** [comment]
请问是怎么处理的

**Comment by ChenSiLiang** [comment]
移除原来有photoview库，或者只依赖于core，自己写界面
